### ISSUE TITLE
Dependency es6-defer uses ES6 syntax (not transpiled)

### ISSUE THREAD

**Issue by niklas-e** [andreyluiz/mui-simple-dialogs#1]
My tests fail because es6-defer uses es6 and does not have transpiled version of it. Could it be changed to e.g. [bluebird](https://www.npmjs.com/package/bluebird) or some other Promise library/polyfill? Or maybe you could just use Promises as is and assume everyone who are concerned will include a Promise polyfill for their project.

`PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode
  at webpack:///~/mui-simple-dialogs/index.js:25487:0 <- tests/test-bundler.js:235809`

**Comment by niklas-e** [comment]
Actually this is also affecting my production build, because UglifyJS does not support ES6+

**Comment by andreyluiz** [comment]
I have the same problem regarding let with Uglify. This is in my roadmap to be fixed for another project where I use this library in the next few days. This fix probably will be done in this library and should fix also for your case.

**Comment by andreyluiz** [comment]
I like the way I'm using defer in this case, but I will end up making a simple implementation to avoid the dependency on es6-defer.

**Comment by andreyluiz** [comment]
@niklas-e It has been fixed in 63cc8ecf8e70420577fcef82597943e6c47074c0. Please, test it with release v0.8.0 and reply back with the result. Thank you.

**Comment by niklas-e** [comment]
@andreyluiz yep, it seems to work now. Now I'm able to finish configurations regarding our continuous integration 👍 
Thank you!

**Comment by andreyluiz** [comment]
Good to know. Cheers.
